name: Śledzik BiteFight

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw

    steps:
      - name: Pobieranie repozytorium
        uses: actions/checkout@v3

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalacja biblioteki
        run: pip install requests

      - name: Uruchomienie skryptu
        run: python sledzik.py

      - name: Zapisywanie zmian i raportu
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Aktualizacja danych - $(date)"
          git pull --rebase --autostash
          git push
